// src/utils/data.ts
import { Product, Category, FilterOption } from "../types";

export const categories: Category[] = [
  { id: "ALL", label: "VIEW ALL" },
  { id: "CLASSIC", label: "ERA: CLASSIC", year: "2008-2012" },
  { id: "MLG", label: "ERA: MLG", year: "2013-2015" },
  { id: "SURREAL", label: "ERA: SURREAL", year: "2016-2020" },
  { id: "DEEPFRIED", label: "STATUS: DECAYED", year: "UNKNOWN" },
];

export const filterOptions: {
  styles: FilterOption[];
  colors: FilterOption[];
  brands: FilterOption[];
  sizes: FilterOption[];
} = {
  styles: [
    { id: "VINTAGE", label: "Vintage" },
    { id: "MODERN", label: "Modern" },
    { id: "STREETWEAR", label: "Streetwear" },
  ],
  colors: [
    { id: "BLACK", label: "Black" },
    { id: "WHITE", label: "White" },
    { id: "GREEN", label: "Green" },
    { id: "GREY", label: "Grey" },
    { id: "NEON", label: "Neon" },
  ],
  brands: [
    { id: "THREADROT", label: "Threadrot" },
    { id: "UNKNOWN_BRAND", label: "Unknown Brand" },
  ],
  sizes: [
    { id: "XS", label: "XS" },
    { id: "S", label: "S" },
    { id: "M", label: "M" },
    { id: "L", label: "L" },
    { id: "XL", label: "XL" },
  ],
};

export const productsData: Product[] = [
  {
    id: 1,
    name: "TROLLFACE.OBJ",
    price: "$30.00",
    era: "2010",
    category: "CLASSIC",
    rot: "5%",
    description:
      "The original troll face object file. Perfect for 3D printing your memes.",
    images: ["/trollface.png"],
    style: "VINTAGE",
    color: "BLACK",
    brand: "THREADROT",
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
    dateAdded: "2024-12-01",
  },
  {
    id: 2,
    name: "DOGE HOODIE",
    price: "$65.00",
    era: "2013",
    category: "MLG",
    rot: "15%",
    description: "Much warm. Very cozy. Wow.",
    images: ["/doge.png"],
    style: "STREETWEAR",
    color: "GREY",
    brand: "THREADROT",
    sizes: ["M", "L", "XL"],
    inStock: true,
    dateAdded: "2024-12-15",
  },
  {
    id: 3,
    name: "PEPE CLASSIC TEE",
    price: "$35.00",
    era: "2008",
    category: "CLASSIC",
    rot: "3%",
    description: "Feels good man. Original rare pepe design.",
    images: ["/pepe.png"],
    style: "VINTAGE",
    color: "GREEN",
    brand: "THREADROT",
    sizes: ["XS", "S", "M", "L"],
    inStock: true,
    dateAdded: "2024-11-20",
  },
  {
    id: 4,
    name: "WOJAK DEPRESSION SHIRT",
    price: "$40.00",
    era: "2018",
    category: "SURREAL",
    rot: "45%",
    description:
      "That feel when no gf. Express your existential dread in style.",
    images: ["/wojak.png"],
    style: "MODERN",
    color: "GREY",
    brand: "THREADROT",
    sizes: ["S", "M", "L", "XL"],
    inStock: false,
    dateAdded: "2024-12-10",
  },
  {
    id: 5,
    name: "SALT BAE VINTAGE TEE",
    price: "$38.00",
    era: "2017",
    category: "SURREAL",
    rot: "25%",
    description: "Season your outfit with some premium salt.",
    images: ["/saltbae.png"],
    style: "VINTAGE",
    color: "WHITE",
    brand: "UNKNOWN_BRAND",
    sizes: ["M", "L", "XL"],
    inStock: true,
    dateAdded: "2024-12-05",
  },
  {
    id: 6,
    name: "GRUMPY CAT MEMORIAL",
    price: "$42.00",
    era: "2012",
    category: "CLASSIC",
    rot: "8%",
    description: "NO. In loving memory of the internet's grumpiest feline.",
    images: ["/whiskers.png"],
    style: "VINTAGE",
    color: "BLACK",
    brand: "THREADROT",
    sizes: ["S", "M", "L"],
    inStock: true,
    dateAdded: "2024-11-25",
  },
  {
    id: 7,
    name: "DISTRACTED BOYFRIEND",
    price: "$36.00",
    era: "2017",
    category: "SURREAL",
    rot: "30%",
    description: "The iconic stock photo that became a meme legend.",
    images: ["/pepe.png"],
    style: "MODERN",
    color: "NEON",
    brand: "THREADROT",
    sizes: ["M", "L", "XL"],
    inStock: true,
    dateAdded: "2024-12-20",
  },
  {
    id: 8,
    name: "HARAMBE TRIBUTE HOODIE",
    price: "$68.00",
    era: "2016",
    category: "SURREAL",
    rot: "22%",
    description: "Dicks out. Never forget.",
    images: ["/doge.png"],
    style: "STREETWEAR",
    color: "BLACK",
    brand: "THREADROT",
    sizes: ["L", "XL"],
    inStock: false,
    dateAdded: "2024-12-08",
  },
  {
    id: 9,
    name: "RICKROLL CLASSIC",
    price: "$33.00",
    era: "2008",
    category: "CLASSIC",
    rot: "2%",
    description: "Never gonna give you up, never gonna let you down.",
    images: ["/trollface.png"],
    style: "VINTAGE",
    color: "WHITE",
    brand: "THREADROT",
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
    dateAdded: "2024-11-18",
  },
  {
    id: 10,
    name: "KEYBOARD CAT VINTAGE",
    price: "$37.00",
    era: "2009",
    category: "CLASSIC",
    rot: "6%",
    description: "Play him off, keyboard cat.",
    images: ["/whiskers.png"],
    style: "VINTAGE",
    color: "GREY",
    brand: "UNKNOWN_BRAND",
    sizes: ["M", "L"],
    inStock: true,
    dateAdded: "2024-12-12",
  },
  {
    id: 11,
    name: "NYAN CAT RAINBOW TEE",
    price: "$39.00",
    era: "2011",
    category: "CLASSIC",
    rot: "10%",
    description: "Nyan nyan nyan nyan. Infinite rainbow trail included.",
    images: ["/whiskers.png"],
    style: "STREETWEAR",
    color: "NEON",
    brand: "THREADROT",
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
    dateAdded: "2024-12-18",
  },
  {
    id: 12,
    name: "OVERLY ATTACHED GF",
    price: "$35.00",
    era: "2012",
    category: "CLASSIC",
    rot: "12%",
    description: "I'll never leave you. Ever.",
    images: ["/pepe.png"],
    style: "MODERN",
    color: "WHITE",
    brand: "THREADROT",
    sizes: ["XS", "S", "M"],
    inStock: false,
    dateAdded: "2024-11-30",
  },
  {
    id: 13,
    name: "SCUMBAG STEVE HAT",
    price: "$28.00",
    era: "2011",
    category: "CLASSIC",
    rot: "7%",
    description: "Borrows your hat, makes it iconic.",
    images: ["/doge.png"],
    style: "STREETWEAR",
    color: "BLACK",
    brand: "UNKNOWN_BRAND",
    sizes: ["M", "L", "XL"],
    inStock: true,
    dateAdded: "2024-12-22",
  },
  {
    id: 14,
    name: "BAD LUCK BRIAN",
    price: "$34.00",
    era: "2012",
    category: "CLASSIC",
    rot: "9%",
    description: "Buys meme shirt. Becomes the meme.",
    images: ["/wojak.png"],
    style: "VINTAGE",
    color: "GREY",
    brand: "THREADROT",
    sizes: ["S", "M", "L"],
    inStock: true,
    dateAdded: "2024-12-03",
  },
  {
    id: 15,
    name: "MOTH LAMP OBSESSION",
    price: "$41.00",
    era: "2018",
    category: "SURREAL",
    rot: "35%",
    description: "LÄMP. The moth's eternal quest.",
    images: ["/pepe.png"],
    style: "MODERN",
    color: "NEON",
    brand: "THREADROT",
    sizes: ["M", "L", "XL"],
    inStock: true,
    dateAdded: "2024-12-25",
  },
  {
    id: 16,
    name: "STONKS GUY BUSINESS",
    price: "$44.00",
    era: "2017",
    category: "SURREAL",
    rot: "28%",
    description: "When your portfolio is up 0.3%. STONKS ↗",
    images: ["/doge.png"],
    style: "STREETWEAR",
    color: "GREEN",
    brand: "THREADROT",
    sizes: ["L", "XL"],
    inStock: true,
    dateAdded: "2024-12-14",
  },
  {
    id: 17,
    name: "WOMAN YELLING AT CAT",
    price: "$38.00",
    era: "2019",
    category: "SURREAL",
    rot: "40%",
    description: "He no talk back. Just eat salad.",
    images: ["/whiskers.png"],
    style: "MODERN",
    color: "WHITE",
    brand: "UNKNOWN_BRAND",
    sizes: ["S", "M", "L"],
    inStock: false,
    dateAdded: "2024-12-07",
  },
  {
    id: 18,
    name: "AREA 51 RAID SURVIVOR",
    price: "$45.00",
    era: "2019",
    category: "SURREAL",
    rot: "38%",
    description: "They can't stop all of us. Commemorative edition.",
    images: ["/trollface.png"],
    style: "STREETWEAR",
    color: "BLACK",
    brand: "THREADROT",
    sizes: ["M", "L", "XL"],
    inStock: true,
    dateAdded: "2024-12-19",
  },
  {
    id: 19,
    name: "E MEME SUPREME",
    price: "$50.00",
    era: "2018",
    category: "DEEPFRIED",
    rot: "85%",
    description: "E. That's it. That's the shirt.",
    images: ["/pepe.png"],
    style: "MODERN",
    color: "NEON",
    brand: "THREADROT",
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
    dateAdded: "2024-12-23",
  },
  {
    id: 20,
    name: "DEEP FRIED SURREAL",
    price: "$55.00",
    era: "2019",
    category: "DEEPFRIED",
    rot: "92%",
    description: "Maximum compression. Minimum pixels. Pure chaos.",
    images: ["/wojak.png"],
    style: "MODERN",
    color: "GREY",
    brand: "UNKNOWN_BRAND",
    sizes: ["M", "L"],
    inStock: false,
    dateAdded: "2024-12-11",
  },
  {
    id: 21,
    name: "MLG MONTAGE PARODY",
    price: "$48.00",
    era: "2014",
    category: "MLG",
    rot: "18%",
    description: "360 no-scope your wardrobe. Airhorns not included.",
    images: ["/doge.png"],
    style: "STREETWEAR",
    color: "NEON",
    brand: "THREADROT",
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
    dateAdded: "2024-12-16",
  },
  {
    id: 22,
    name: "SAMPLE TEXT HOODIE",
    price: "$62.00",
    era: "2013",
    category: "MLG",
    rot: "16%",
    description: "Impact font in white with black outline. Classic.",
    images: ["/trollface.png"],
    style: "VINTAGE",
    color: "BLACK",
    brand: "THREADROT",
    sizes: ["L", "XL"],
    inStock: true,
    dateAdded: "2024-12-21",
  },
  {
    id: 23,
    name: "PRESS F TO PAY RESPECTS",
    price: "$36.00",
    era: "2014",
    category: "MLG",
    rot: "14%",
    description: "F in the chat. The ultimate tribute.",
    images: ["/wojak.png"],
    style: "MODERN",
    color: "WHITE",
    brand: "THREADROT",
    sizes: ["S", "M", "L"],
    inStock: true,
    dateAdded: "2024-12-24",
  },
  {
    id: 24,
    name: "DESTRUCTION 100",
    price: "$40.00",
    era: "2011",
    category: "CLASSIC",
    rot: "11%",
    description: "Skyrim skill meme. Legendary roast energy.",
    images: ["/pepe.png"],
    style: "VINTAGE",
    color: "GREEN",
    brand: "UNKNOWN_BRAND",
    sizes: ["M", "L", "XL"],
    inStock: true,
    dateAdded: "2024-12-09",
  },
];
